### ISSUE TITLE
Cant open EURUSD

### ISSUE THREAD

**Issue by juantomas12** [brian-the-dev/tradingview-ta-demo#6]
![image](https://user-images.githubusercontent.com/59766799/208665004-e77e0fbc-e8dd-48e9-9139-9b319cbd0020.png)

![image](https://user-images.githubusercontent.com/59766799/208665123-890ffbbd-83b1-4d69-adae-9f0a42ceef7b.png)

symbol or exange fail.. i dont understand it

**Comment by brian-the-dev** [comment]
Try `FX_IDC` as the exchange.

**Comment by juantomas12** [comment]
Solved!! Thanks!!!!
